method: random
metric:
  goal: minimize
  name: train_loss
early_terminate:
  type: hyperband
  min_iter: 30
  eta: 3
  max_iter: 250
parameters:
  batch_size:
    values: [32, 64, 128]
  ff_size:
    values: [8, 16, 32, 64, 128, 256]
  dropout:
    distribution: "uniform"
    min: 0.1
    max: 0.3
  learning_rate:
    distribution: "uniform"
    min: 0
    max: 0.001
  num_heads:
    values: [1, 2, 4]
  comp_seq_len:
    values: [128, 256, 512]
  num_layers:
    distribution: "int_uniform"
    min: 1
    max: 8
command:
  - ${env}
  - python3
  - src/train.py
  - "-hp"
  - "src/configs/transformer.yaml"
project: "faab_autoencoder_transformer_time"
description: ""
