project: "faab_jan_autoencoder_test"
# dataset parameters
pickle_path: "src/dataset/data/01171105/0117_processed_mediumtest_1024.pkl"
pred: False
seq_len: 1024
batch_size: 5

# common model parameters
feat_in_size: 8 # feature size
d_model: 4 # must be divisible by num_heads
ff_size: 256
num_layers: 4

# model parameters transformer
model: "transformer"
num_heads: 2
pe_scale_factor: 1.0
mask: False

# training parameters
max_grad_norm: 1
dropout: 0.1
epochs: 500
optimizer: "rmsprop"
learning_rate: 0.0001
scheduler_step_size: 2
scheduler_gamma: 0.1
plotter_samples: 5
