project: "faab_jan_autoencoder_time_test"
# dataset parameters
pickle_path: "src/dataset/data/01171105/0117_processed_mediumtest_1024.pkl"
weights_path: "src/dataset/data/0117/weights.pkl"
pred: False
seq_len: 1024
comp_seq_len: 512
batch_size: 5

# common model parameters
feat_len: 8 # feature size
comp_feat_len: 4 # must be divisible by num_heads
ff_size: 256
num_layers: 4

# model parameters transformer
model: "transformer"
num_heads: 2
pe_scale_factor: 1.0
mask: False

# training parameters
max_grad_norm: 1
dropout: 0.1
epochs: 100
optimizer: "rmsprop"
criterion: "weighted_mse"
learning_rate: 0.001
scheduler_step_size: 2
scheduler_gamma: 0.1
plotter_samples: 5
